lee_controller:
  ros__parameters:
    model_name: "iris"
    control_rate: 100.0
    rate: 100.0         
    motor_num: 4
    inertia: [0.0347563, 0.0458929, 0.0977]
    # kp: [15.0, 15.0, 15.0]
    # kd: [5.7, 5.7, 5.7]
    # attitude_gain: [2.0, 3.0, 0.15]
    # angular_rate_gain: [0.4, 0.52, 0.18]
    kp: [7.0,7.0,6.0]                            #<--px4 kz=15
    kd: [6.0, 6.0, 3.0]                             #<--px4
    attitude_gain: [3.0, 3.0, 0.15]                  #<--px4
    angular_rate_gain: [0.5, 0.5, 0.18]              #<--px4
    mass: 1.515
    gravity: 9.81
    # motor_force_k: 8.54858e-06
    # motor_moment_k: 1.6e-2
    # rotor_angles: [-0.5337, 2.565, 0.5337, -2.565]
    # arm_length:  [0.255, 0.238, 0.255, 0.238]
    motor_force_k: 5.84e-06                         #<--px4
    motor_moment_k: 0.06                            #<--px4
    rotor_angles: [ 0.5337, -2.565, 2.565, -0.5337] #<--px4
    arm_length:   [ 0.255, 0.238, 0.238, 0.255]     #<--px4
    
    motor_rotation_direction: [1.0, 1.0, -1.0, -1.0]

    ref_jerk_max: 10.0
    ref_acc_max: 2.5
    ref_vel_max: 2.0
    ref_omega: 1.0
    ref_zita: 0.75

    ref_o_jerk_max: 2.0
    ref_o_acc_max: 0.8
    ref_o_vel_max: 0.05


